sudo: required
language: ruby
services:
- docker
cache:
- bundler
before_install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - gem install bundler -v 1.15
install:
- bundle install
rvm:
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
  - gem build sensu-plugins-jolokia-metrics.gemspec
  - gem install sensu-plugins-jolokia-metrics-*.gem
  - bundle exec rake quick
  - bundle exec rake kitchen:ruby-`echo $TRAVIS_RUBY_VERSION | sed -e "s/\.//g"`-debian-8
before_deploy:
- bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'; cp asset_build_scripts/Dockerfile.* bonsai/ruby-runtime/"
deploy:
- provider: rubygems
  api_key:
    secure: BBqXqAluZs6sKpaSt/za1P1KSbn0BuF4aB78iyL1wiqms8AXEmu6Y7ifY02EsyEI4vjgrTF2qtmNauvrE7myC7C0Qs56Ds5ZrdLZO8HTbO4RhRZuX69zpac540EXJ14EM89kgOhOJFeTdVvlfcmyfvXNhxiX6MO9dxwjXYEjF9kSSN6dsAD5FJKN17wzG6fxEVj551IOyiYXVtuqXKNkpMlEpvAubFfJA20IGewZFnhaNDx/zFhFmLfr3qvrNkJCeoK8vbzS1RStwR6wLxYL4eIE8XUnAIgbJ4bS0F5sLR6lxCN3vcAIetq7VX91MlyxeP5mTFzcKCB4f0iHLH81IHnZTUb6Q5yju3Mz2GwsQp6AWYmKyjL3Ak1pjmUkw18JVq3DRaZfNrXASo/FjGgM2PsPd94KLdGgYJKze6nkjvcg1EjQNNDIshfytqL8CdnXIt1H6bi749Q+BFyosShuYdOdDIORdK5ZHQtRDmqQCllVsi7YVKzACoia99WzVs8wbi/eLxGjo4L208XwVDrItbMDNNzvpZ0cTfczA2oN4bFbI8nUXpUdK71lyictZpczR+bD+8gKFC+GUyv20o39kVfP6KXDJIdOaXoP8MwoJQS5GKYUS62F98UA/ydSi+IWIo/Yf/b4Mab9kTti1SuxND03jI5sA+NCz0KbX2T0kuY=
  gem: sensu-plugins-jolokia-metrics
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
    repo: fgouteroux/sensu-plugins-jolokia-metrics
- provider: script
  script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-jolokia-metrics
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    rvm: 2.4.1
env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
